schema_version: 20180708
name: sentiments-analytics
version: 0.0.1
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk9-1.0.70
run_image: fnproject/fn-java-fdk:jdk9-1.0.70
cmd: com.fn.sentiments.HelloFunction::handleRequest
memory: 512
format: http-stream
triggers:
- name: sentiments-analytics-trigger
  type: http
  source: /analyze
